/** Pool amplio de jugadores para feeds en vivo (nombres variados, LATAM + España). */

export type LivePlayer = {
  handle: string;
  flag: string;
  place?: string;
};

const CORE_LIVE_PLAYERS: LivePlayer[] = [
  { handle: "@lucia.m", flag: "🇦🇷", place: "CABA" },
  { handle: "@carlos_v", flag: "🇲🇽", place: "CDMX" },
  { handle: "@maria.g", flag: "🇨🇴", place: "Medellín" },
  { handle: "@diego.s", flag: "🇨🇱", place: "Santiago" },
  { handle: "@vale_r", flag: "🇦🇷", place: "Rosario" },
  { handle: "@mateo.f", flag: "🇵🇪", place: "Lima" },
  { handle: "@sofia_b", flag: "🇺🇾" },
  { handle: "@nicolas.h", flag: "🇧🇷", place: "SP" },
  { handle: "@camila.w", flag: "🇪🇸", place: "Madrid" },
  { handle: "@gabriel.t", flag: "🇲🇽", place: "Guadalajara" },
  { handle: "@ana.r", flag: "🇨🇴" },
  { handle: "@pablo.k", flag: "🇦🇷", place: "Córdoba" },
  { handle: "@julieta_ok", flag: "🇦🇷" },
  { handle: "@martin.lp", flag: "🇺🇾", place: "Montevideo" },
  { handle: "@renata.m", flag: "🇧🇷", place: "Rio" },
  { handle: "@thiago.n", flag: "🇧🇷" },
  { handle: "@elena_p", flag: "🇪🇸", place: "Barcelona" },
  { handle: "@jorge_h", flag: "🇵🇪" },
  { handle: "@patri.c", flag: "🇨🇱" },
  { handle: "@damian.z", flag: "🇦🇷", place: "Mendoza" },
  { handle: "@flor.99", flag: "🇦🇷" },
  { handle: "@ricardo_m", flag: "🇲🇽" },
  { handle: "@isa.bel", flag: "🇨🇴", place: "Bogotá" },
  { handle: "@tomas_g", flag: "🇨🇱" },
  { handle: "@mica_s", flag: "🇦🇷" },
  { handle: "@leo.mendez", flag: "🇲🇽" },
  { handle: "@cande.r", flag: "🇦🇷", place: "La Plata" },
  { handle: "@bruno_f", flag: "🇧🇷" },
  { handle: "@lorena.v", flag: "🇪🇸" },
  { handle: "@agus.t", flag: "🇦🇷" },
  { handle: "@fede_ok", flag: "🇺🇾" },
  { handle: "@romina.k", flag: "🇦🇷" },
  { handle: "@sebas_p", flag: "🇨🇴" },
  { handle: "@nati.w", flag: "🇦🇷" },
  { handle: "@ivan_h", flag: "🇵🇪", place: "Arequipa" },
  { handle: "@paula.m", flag: "🇨🇱" },
  { handle: "@maxi.r", flag: "🇦🇷" },
  { handle: "@dani_lo", flag: "🇲🇽" },
  { handle: "@cris.v", flag: "🇦🇷" },
  { handle: "@lau_b", flag: "🇨🇴" },
  { handle: "@nico.uy", flag: "🇺🇾" },
  { handle: "@vale_mx", flag: "🇲🇽" },
  { handle: "@juampi", flag: "🇦🇷" },
  { handle: "@meli.s", flag: "🇧🇷" },
  { handle: "@adrian.c", flag: "🇪🇸" },
  { handle: "@caro_p", flag: "🇦🇷" },
  { handle: "@hugo_m", flag: "🇵🇪" },
  { handle: "@silvia.r", flag: "🇨🇱" },
  { handle: "@omar.t", flag: "🇲🇽" },
  { handle: "@yazmin", flag: "🇨🇴" },
  { handle: "@facu_river", flag: "🇦🇷", place: "San Isidro" },
  { handle: "@belu_ok", flag: "🇦🇷" },
  { handle: "@mati.zz", flag: "🇦🇷", place: "Tigre" },
  { handle: "@santi.gomez", flag: "🇦🇷" },
  { handle: "@luu.cas", flag: "🇦🇷", place: "Mar del Plata" },
  { handle: "@nacho.fit", flag: "🇦🇷" },
  { handle: "@male_san", flag: "🇦🇷", place: "Salta" },
  { handle: "@tizi.22", flag: "🇦🇷" },
  { handle: "@ezequiel.r", flag: "🇦🇷", place: "Neuquén" },
  { handle: "@pili_m", flag: "🇦🇷" },
  { handle: "@rodri.lp", flag: "🇦🇷" },
  { handle: "@valeen.ok", flag: "🇦🇷", place: "Córdoba" },
  { handle: "@fran_cba", flag: "🇦🇷" },
  { handle: "@guada.s", flag: "🇦🇷" },
  { handle: "@lean.d", flag: "🇦🇷", place: "Bahía Blanca" },
  { handle: "@sofi_travel", flag: "🇦🇷" },
  { handle: "@martu.x", flag: "🇦🇷" },
  { handle: "@juanpi.99", flag: "🇦🇷" },
  { handle: "@cami_ros", flag: "🇦🇷", place: "Santa Fe" },
  { handle: "@nico_boca", flag: "🇦🇷" },
  { handle: "@delfi_ok", flag: "🇦🇷" },
  { handle: "@agus_pro", flag: "🇦🇷" },
  { handle: "@lucho_m", flag: "🇦🇷", place: "Tucumán" },
  { handle: "@mili_v", flag: "🇦🇷" },
  { handle: "@tomi_sk8", flag: "🇦🇷" },
  { handle: "@brenda.r", flag: "🇦🇷" },
  { handle: "@kevin.ar", flag: "🇦🇷", place: "Pilar" },
  { handle: "@ayelen.s", flag: "🇦🇷" },
  { handle: "@joaco_ok", flag: "🇦🇷" },
  { handle: "@romi.88", flag: "🇦🇷" },
  { handle: "@fede_gym", flag: "🇦🇷" },
  { handle: "@vero_lp", flag: "🇦🇷", place: "La Plata" },
  { handle: "@alan.zz", flag: "🇦🇷" },
  { handle: "@dai_ok", flag: "🇦🇷" },
  { handle: "@gus_trader", flag: "🇦🇷" },
  { handle: "@nati_cas", flag: "🇦🇷" },
  { handle: "@pato_r", flag: "🇦🇷", place: "Quilmes" },
  { handle: "@luli.x", flag: "🇦🇷" },
  { handle: "@marce_ok", flag: "🇦🇷" },
  { handle: "@seba_fit", flag: "🇦🇷" },
  { handle: "@andrea.v", flag: "🇲🇽", place: "Monterrey" },
  { handle: "@luis_mx", flag: "🇲🇽" },
  { handle: "@ximena.r", flag: "🇲🇽", place: "Puebla" },
  { handle: "@fer_cdmx", flag: "🇲🇽" },
  { handle: "@alejandra_ok", flag: "🇲🇽" },
  { handle: "@javi_mx", flag: "🇲🇽", place: "Tijuana" },
  { handle: "@diana_lo", flag: "🇲🇽" },
  { handle: "@miguel.t", flag: "🇲🇽" },
  { handle: "@paola_mx", flag: "🇲🇽", place: "León" },
  { handle: "@raul_99", flag: "🇲🇽" },
  { handle: "@sara_mx", flag: "🇲🇽" },
  { handle: "@edgar.ok", flag: "🇲🇽", place: "Cancún" },
  { handle: "@moni.r", flag: "🇲🇽" },
  { handle: "@hector_mx", flag: "🇲🇽" },
  { handle: "@lupita_s", flag: "🇲🇽", place: "Mérida" },
  { handle: "@arturo_mx", flag: "🇲🇽" },
  { handle: "@claudia.v", flag: "🇲🇽" },
  { handle: "@roberto_ok", flag: "🇲🇽" },
  { handle: "@yolanda_mx", flag: "🇲🇽" },
  { handle: "@ivan_mx", flag: "🇲🇽", place: "Querétaro" },
  { handle: "@karen_mx", flag: "🇲🇽" },
  { handle: "@oscar.t", flag: "🇲🇽" },
  { handle: "@wendy_mx", flag: "🇲🇽" },
  { handle: "@brandon_mx", flag: "🇲🇽", place: "Culiacán" },
  { handle: "@natalia_mx", flag: "🇲🇽" },
  { handle: "@cesar_ok", flag: "🇲🇽" },
  { handle: "@mariana_mx", flag: "🇲🇽" },
  { handle: "@diego_mx99", flag: "🇲🇽", place: "Aguascalientes" },
  { handle: "@sof_mx", flag: "🇲🇽" },
  { handle: "@juan_carlos_mx", flag: "🇲🇽" },
  { handle: "@andres_co", flag: "🇨🇴", place: "Cali" },
  { handle: "@sara_co", flag: "🇨🇴" },
  { handle: "@felipe_co", flag: "🇨🇴", place: "Barranquilla" },
  { handle: "@lina_co", flag: "🇨🇴" },
  { handle: "@david_co", flag: "🇨🇴" },
  { handle: "@valentina_co", flag: "🇨🇴", place: "Cartagena" },
  { handle: "@jhon_co", flag: "🇨🇴" },
  { handle: "@karen_co", flag: "🇨🇴" },
  { handle: "@santiago_co", flag: "🇨🇴", place: "Bucaramanga" },
  { handle: "@diana_co", flag: "🇨🇴" },
  { handle: "@camilo_co", flag: "🇨🇴" },
  { handle: "@paola_co", flag: "🇨🇴" },
  { handle: "@sebastian_co", flag: "🇨🇴", place: "Pereira" },
  { handle: "@mariana_co", flag: "🇨🇴" },
  { handle: "@nicolas_co", flag: "🇨🇴" },
  { handle: "@juliana_co", flag: "🇨🇴" },
  { handle: "@mateo_co", flag: "🇨🇴" },
  { handle: "@laura_co", flag: "🇨🇴", place: "Manizales" },
  { handle: "@esteban_co", flag: "🇨🇴" },
  { handle: "@angie_co", flag: "🇨🇴" },
  { handle: "@carlos_co99", flag: "🇨🇴" },
  { handle: "@paula_cl", flag: "🇨🇱", place: "Valparaíso" },
  { handle: "@matias_cl", flag: "🇨🇱" },
  { handle: "@fernanda_cl", flag: "🇨🇱", place: "Viña" },
  { handle: "@benjamin_cl", flag: "🇨🇱" },
  { handle: "@carolina_cl", flag: "🇨🇱" },
  { handle: "@jose_cl", flag: "🇨🇱", place: "Concepción" },
  { handle: "@camila_cl", flag: "🇨🇱" },
  { handle: "@ignacio_cl", flag: "🇨🇱" },
  { handle: "@francisca_cl", flag: "🇨🇱", place: "La Serena" },
  { handle: "@rodrigo_cl", flag: "🇨🇱" },
  { handle: "@javiera_cl", flag: "🇨🇱" },
  { handle: "@felipe_cl", flag: "🇨🇱" },
  { handle: "@constanza_cl", flag: "🇨🇱", place: "Antofagasta" },
  { handle: "@sebastian_cl", flag: "🇨🇱" },
  { handle: "@barbara_cl", flag: "🇨🇱" },
  { handle: "@cristian_cl", flag: "🇨🇱" },
  { handle: "@valeria_cl", flag: "🇨🇱", place: "Temuco" },
  { handle: "@marco_pe", flag: "🇵🇪", place: "Trujillo" },
  { handle: "@lucia_pe", flag: "🇵🇪" },
  { handle: "@carlos_pe", flag: "🇵🇪", place: "Cusco" },
  { handle: "@andrea_pe", flag: "🇵🇪" },
  { handle: "@diego_pe", flag: "🇵🇪" },
  { handle: "@rosa_pe", flag: "🇵🇪", place: "Piura" },
  { handle: "@miguel_pe", flag: "🇵🇪" },
  { handle: "@paola_pe", flag: "🇵🇪" },
  { handle: "@fernando_pe", flag: "🇵🇪", place: "Iquitos" },
  { handle: "@gabriela_pe", flag: "🇵🇪" },
  { handle: "@ricardo_pe", flag: "🇵🇪" },
  { handle: "@elena_pe", flag: "🇵🇪" },
  { handle: "@javier_pe", flag: "🇵🇪", place: "Chiclayo" },
  { handle: "@ana_pe", flag: "🇵🇪" },
  { handle: "@bruno_br", flag: "🇧🇷", place: "BH" },
  { handle: "@julia_br", flag: "🇧🇷" },
  { handle: "@rafa_br", flag: "🇧🇷", place: "Curitiba" },
  { handle: "@larissa_br", flag: "🇧🇷" },
  { handle: "@gustavo_br", flag: "🇧🇷", place: "Brasília" },
  { handle: "@amanda_br", flag: "🇧🇷" },
  { handle: "@felipe_br", flag: "🇧🇷", place: "Fortaleza" },
  { handle: "@beatriz_br", flag: "🇧🇷" },
  { handle: "@leonardo_br", flag: "🇧🇷" },
  { handle: "@carla_br", flag: "🇧🇷", place: "Salvador" },
  { handle: "@vinicius_br", flag: "🇧🇷" },
  { handle: "@marina_br", flag: "🇧🇷", place: "Recife" },
  { handle: "@pedro_br", flag: "🇧🇷" },
  { handle: "@isabela_br", flag: "🇧🇷" },
  { handle: "@lucas_br99", flag: "🇧🇷", place: "Porto Alegre" },
  { handle: "@camila_br", flag: "🇧🇷" },
  { handle: "@rodrigo_br", flag: "🇧🇷" },
  { handle: "@fernanda_br", flag: "🇧🇷", place: "Manaus" },
  { handle: "@thiago_br", flag: "🇧🇷" },
  { handle: "@bianca_br", flag: "🇧🇷" },
  { handle: "@mateus_br", flag: "🇧🇷" },
  { handle: "@leticia_br", flag: "🇧🇷", place: "Florianópolis" },
  { handle: "@diego_uy", flag: "🇺🇾" },
  { handle: "@valentina_uy", flag: "🇺🇾", place: "Punta del Este" },
  { handle: "@santiago_uy", flag: "🇺🇾" },
  { handle: "@florencia_uy", flag: "🇺🇾" },
  { handle: "@matias_uy", flag: "🇺🇾", place: "Colonia" },
  { handle: "@lucia_uy", flag: "🇺🇾" },
  { handle: "@pablo_uy", flag: "🇺🇾" },
  { handle: "@carla_es", flag: "🇪🇸", place: "Valencia" },
  { handle: "@javier_es", flag: "🇪🇸" },
  { handle: "@lucia_es", flag: "🇪🇸", place: "Sevilla" },
  { handle: "@miguel_es", flag: "🇪🇸" },
  { handle: "@ana_es", flag: "🇪🇸", place: "Bilbao" },
  { handle: "@david_es", flag: "🇪🇸" },
  { handle: "@paula_es", flag: "🇪🇸", place: "Málaga" },
  { handle: "@sergio_es", flag: "🇪🇸" },
  { handle: "@marta_es", flag: "🇪🇸", place: "Zaragoza" },
  { handle: "@alvaro_es", flag: "🇪🇸" },
  { handle: "@cristina_es", flag: "🇪🇸" },
  { handle: "@ruben_es", flag: "🇪🇸", place: "Alicante" },
  { handle: "@nuria_es", flag: "🇪🇸" },
  { handle: "@pablo_ec", flag: "🇪🇨", place: "Quito" },
  { handle: "@andrea_ec", flag: "🇪🇨" },
  { handle: "@carlos_ec", flag: "🇪🇨", place: "Guayaquil" },
  { handle: "@diana_ec", flag: "🇪🇨" },
  { handle: "@jose_ve", flag: "🇻🇪", place: "Caracas" },
  { handle: "@maria_ve", flag: "🇻🇪" },
  { handle: "@luis_ve", flag: "🇻🇪", place: "Maracaibo" },
  { handle: "@ana_ve", flag: "🇻🇪" },
  { handle: "@carlos_pa", flag: "🇵🇦" },
  { handle: "@sofia_pa", flag: "🇵🇦", place: "Ciudad de Panamá" },
  { handle: "@diego_cr", flag: "🇨🇷", place: "San José" },
  { handle: "@laura_cr", flag: "🇨🇷" },
  { handle: "@juan_do", flag: "🇩🇴", place: "Santo Domingo" },
  { handle: "@maria_do", flag: "🇩🇴" },
  { handle: "@carlos_gt", flag: "🇬🇹", place: "Guatemala" },
  { handle: "@ana_gt", flag: "🇬🇹" },
  { handle: "@pedro_bo", flag: "🇧🇴", place: "La Paz" },
  { handle: "@lucia_bo", flag: "🇧🇴" },
  { handle: "@mateo_py", flag: "🇵🇾", place: "Asunción" },
  { handle: "@valentina_py", flag: "🇵🇾" },
  { handle: "@user_2847", flag: "🇦🇷" },
  { handle: "@user_9103", flag: "🇲🇽" },
  { handle: "@user_5521", flag: "🇨🇴" },
  { handle: "@user_7734", flag: "🇧🇷" },
  { handle: "@user_4412", flag: "🇨🇱" },
  { handle: "@user_8890", flag: "🇵🇪" },
  { handle: "@user_3319", flag: "🇪🇸" },
  { handle: "@user_6628", flag: "🇺🇾" },
  { handle: "@lucky_star_07", flag: "🇦🇷" },
  { handle: "@moon_player_23", flag: "🇲🇽" },
  { handle: "@portal_fan_88", flag: "🇨🇴" },
  { handle: "@crypto_luna_12", flag: "🇧🇷" },
  { handle: "@fortuna_x_45", flag: "🇨🇱" },
  { handle: "@mystik_gamer", flag: "🇦🇷" },
  { handle: "@jackpot_hunter", flag: "🇲🇽" },
  { handle: "@galleta_king", flag: "🇵🇪" },
  { handle: "@triple_luna_fan", flag: "🇦🇷" },
  { handle: "@slot_master_99", flag: "🇧🇷" },
  { handle: "@premio_rapido", flag: "🇨🇴" },
  { handle: "@suerte_latam", flag: "🇺🇾" },
  { handle: "@ganador_anon_42", flag: "🇦🇷" },
  { handle: "@player_noche", flag: "🇲🇽" },
  { handle: "@mesa_caliente", flag: "🇨🇱" },
  { handle: "@giro_dorado", flag: "🇪🇸" },
  { handle: "@carrete_pro", flag: "🇦🇷" },
  { handle: "@linea_pago_ok", flag: "🇧🇷" },
  { handle: "@portal_vip_01", flag: "🇲🇽" },
  { handle: "@usuario_activo", flag: "🇨🇴" },
  { handle: "@jugador_247", flag: "🇵🇪" },
  { handle: "@noche_jackpot", flag: "🇦🇷" },
  { handle: "@spin_rapido", flag: "🇧🇷" },
  { handle: "@dolar_verde", flag: "🇲🇽" },
  { handle: "@corazon_triple", flag: "🇨🇴" },
  { handle: "@orbe_fan_cl", flag: "🇨🇱" },
  { handle: "@maria_del_sur", flag: "🇦🇷", place: "Patagonia" },
  { handle: "@el_chino_mx", flag: "🇲🇽" },
  { handle: "@la_paisa_co", flag: "🇨🇴", place: "Medellín" },
  { handle: "@porteno_ok", flag: "🇦🇷", place: "CABA" },
  { handle: "@carioca_br", flag: "🇧🇷", place: "Rio" },
  { handle: "@chileno_real", flag: "🇨🇱" },
  { handle: "@peruano_trader", flag: "🇵🇪" },
  { handle: "@uruguayo_uy", flag: "🇺🇾" },
  { handle: "@madrid_noche", flag: "🇪🇸", place: "Madrid" },
  { handle: "@barca_fan_es", flag: "🇪🇸", place: "Barcelona" },
  { handle: "@rosario_central", flag: "🇦🇷", place: "Rosario" },
  { handle: "@cordobes_ok", flag: "🇦🇷", place: "Córdoba" },
  { handle: "@mendocino_wine", flag: "🇦🇷", place: "Mendoza" },
  { handle: "@tucuano_99", flag: "🇦🇷", place: "Tucumán" },
  { handle: "@platense_lp", flag: "🇦🇷", place: "La Plata" },
  { handle: "@monterrey_mx", flag: "🇲🇽", place: "Monterrey" },
  { handle: "@jalisco_mx", flag: "🇲🇽", place: "Guadalajara" },
  { handle: "@yucateco_mx", flag: "🇲🇽", place: "Mérida" },
  { handle: "@paisa_med", flag: "🇨🇴", place: "Medellín" },
  { handle: "@rola_bogota", flag: "🇨🇴", place: "Bogotá" },
  { handle: "@santiaguino", flag: "🇨🇱", place: "Santiago" },
  { handle: "@limeño_pe", flag: "🇵🇪", place: "Lima" },
  { handle: "@paulista_sp", flag: "🇧🇷", place: "SP" },
  { handle: "@gaúcho_rs", flag: "🇧🇷", place: "Porto Alegre" },
  { handle: "@montevideo_uy", flag: "🇺🇾", place: "Montevideo" },
  { handle: "@andaluz_es", flag: "🇪🇸", place: "Sevilla" },
  { handle: "@gallego_es", flag: "🇪🇸" },
  { handle: "@catracho_hn", flag: "🇭🇳" },
  { handle: "@salvadoreño_sv", flag: "🇸🇻" },
  { handle: "@nicaragüense_ni", flag: "🇳🇮" },
  { handle: "@paraguayo_py", flag: "🇵🇾" },
  { handle: "@boliviano_bo", flag: "🇧🇴" },
  { handle: "@ecuatoriano_ec", flag: "🇪🇨" },
  { handle: "@venezolano_ve", flag: "🇻🇪" },
  { handle: "@panameño_pa", flag: "🇵🇦" },
  { handle: "@costarricense_cr", flag: "🇨🇷" },
  { handle: "@dominicano_do", flag: "🇩🇴" },
  { handle: "@guatemalteco_gt", flag: "🇬🇹" },
  { handle: "@aaron.k", flag: "🇺🇸" },
  { handle: "@mike_trades", flag: "🇺🇸" },
  { handle: "@sarah_us", flag: "🇺🇸" },
  { handle: "@emma_play", flag: "🇬🇧" },
  { handle: "@james_uk", flag: "🇬🇧" },
  { handle: "@luca_it", flag: "🇮🇹" },
  { handle: "@marie_fr", flag: "🇫🇷" },
  { handle: "@hans_de", flag: "🇩🇪" },
  { handle: "@ana_pt", flag: "🇵🇹" },
  { handle: "@joao_pt", flag: "🇵🇹", place: "Lisboa" },
  { handle: "@kpop_fan_kr", flag: "🇰🇷" },
  { handle: "@yuki_jp", flag: "🇯🇵" },
  { handle: "@wei_cn", flag: "🇨🇳" },
  { handle: "@raj_in", flag: "🇮🇳" },
  { handle: "@ahmed_ae", flag: "🇦🇪" },
  { handle: "@zara_pk", flag: "🇵🇰" },
  { handle: "@nina_ru", flag: "🇷🇺" },
  { handle: "@olek_pl", flag: "🇵🇱" },
  { handle: "@jan_nl", flag: "🇳🇱" },
  { handle: "@sofie_se", flag: "🇸🇪" },
  { handle: "@erik_no", flag: "🇳🇴" },
  { handle: "@mika_fi", flag: "🇫🇮" },
  { handle: "@lars_dk", flag: "🇩🇰" },
  { handle: "@elias_ch", flag: "🇨🇭" },
  { handle: "@marco_at", flag: "🇦🇹" },
  { handle: "@petra_cz", flag: "🇨🇿" },
  { handle: "@bence_hu", flag: "🇭🇺" },
  { handle: "@ion_ro", flag: "🇷🇴" },
  { handle: "@nikos_gr", flag: "🇬🇷" },
  { handle: "@yusuf_tr", flag: "🇹🇷" },
  { handle: "@amir_il", flag: "🇮🇱" },
  { handle: "@noah_ca", flag: "🇨🇦" },
  { handle: "@chloe_au", flag: "🇦🇺" },
  { handle: "@liam_nz", flag: "🇳🇿" },
  { handle: "@zoe_za", flag: "🇿🇦" },
  { handle: "@kwame_gh", flag: "🇬🇭" },
  { handle: "@amara_ng", flag: "🇳🇬" },
  { handle: "@kenya_ke", flag: "🇰🇪" },
  { handle: "@morocco_ma", flag: "🇲🇦" },
  { handle: "@cairo_eg", flag: "🇪🇬" },
];

const GEN_FIRST = [
  "lucia", "carlos", "maria", "diego", "valentina", "mateo", "sofia", "nicolas",
  "camila", "gabriel", "ana", "pablo", "julieta", "martin", "renata", "thiago",
  "elena", "jorge", "patricia", "damian", "florencia", "ricardo", "isabel", "tomas",
  "micaela", "leonardo", "candela", "bruno", "lorena", "agustin", "federico", "romina",
  "sebastian", "natalia", "ivan", "paula", "maximo", "daniela", "cristian", "laura",
  "juan", "melina", "adrian", "carolina", "hugo", "silvia", "omar", "yazmin", "facundo",
  "belen", "matias", "santiago", "luciano", "ignacio", "male", "tiziana", "ezequiel",
  "pilu", "rodrigo", "valen", "franco", "guadalupe", "leandro", "martina", "juanpi",
  "cami", "delfina", "lucho", "milagros", "tomasito", "brenda", "kevin", "ayelen",
  "joaco", "romi", "veronica", "alan", "daiana", "gustavo", "patricia", "marcelo",
  "luis", "ximena", "fernando", "alejandra", "javier", "diana", "miguel", "paola",
  "raul", "sara", "edgar", "monica", "hector", "guadalupe", "arturo", "claudia",
  "roberto", "yolanda", "karen", "oscar", "wendy", "brandon", "natalia", "cesar",
  "mariana", "andres", "felipe", "lina", "david", "jhon", "camilo", "juliana",
  "esteban", "angie", "matias", "fernanda", "benjamin", "javiera", "constanza",
  "marco", "rosa", "gabriela", "julia", "rafael", "larissa", "gustavo", "amanda",
  "beatriz", "vinicius", "marina", "pedro", "isabela", "leticia", "florencia",
  "javier", "lucia", "miguel", "ana", "david", "paula", "sergio", "marta",
  "alvaro", "cristina", "ruben", "nuria", "pablo", "andrea", "carlos", "diana",
  "jose", "luis", "ana", "carlos", "sofia", "diego", "laura", "juan", "maria",
  "pedro", "lucia", "mateo", "valentina", "santi", "nico", "vale", "fede", "agus",
  "luu", "tizi", "nacho", "pili", "guada", "lean", "martu", "delfi", "mili",
  "tomi", "brenda", "ayelen", "joaco", "vero", "dai", "gus", "pato", "luli",
  "marce", "seba", "andrea", "fer", "javi", "dani", "mono", "lau", "juampi",
  "meli", "caro", "hugo", "sil", "omar", "yazi", "benja", "cande", "rodri",
  "flor", "isa", "tomi", "leo", "maxi", "cris", "nati", "ivan", "pau", "max",
];

const GEN_LAST = [
  "gomez", "lopez", "martinez", "rodriguez", "fernandez", "garcia", "sanchez",
  "torres", "ramirez", "flores", "rivera", "morales", "cruz", "reyes", "ortiz",
  "silva", "santos", "oliveira", "costa", "pereira", "alves", "lima", "souza",
  "rocha", "dias", "castro", "vargas", "herrera", "medina", "aguilar", "vega",
  "rios", "mendez", "ruiz", "diaz", "romero", "navarro", "molina", "suarez",
  "ibarra", "paredes", "campos", "nunez", "vera", "paz", "leon", "soto", "vera",
  "rios", "cano", "luna", "sol", "mar", "rey", "reyes", "king", "star", "play",
  "mx", "ar", "co", "cl", "pe", "br", "uy", "es", "ok", "pro", "fan", "vip",
];

const GEN_FLAGS: { flag: string; place?: string }[] = [
  { flag: "🇦🇷", place: "CABA" },
  { flag: "🇦🇷", place: "Rosario" },
  { flag: "🇦🇷", place: "Córdoba" },
  { flag: "🇦🇷", place: "Mendoza" },
  { flag: "🇦🇷", place: "La Plata" },
  { flag: "🇦🇷" },
  { flag: "🇲🇽", place: "CDMX" },
  { flag: "🇲🇽", place: "Monterrey" },
  { flag: "🇲🇽", place: "Guadalajara" },
  { flag: "🇲🇽" },
  { flag: "🇨🇴", place: "Bogotá" },
  { flag: "🇨🇴", place: "Medellín" },
  { flag: "🇨🇴", place: "Cali" },
  { flag: "🇨🇴" },
  { flag: "🇨🇱", place: "Santiago" },
  { flag: "🇨🇱", place: "Valparaíso" },
  { flag: "🇨🇱" },
  { flag: "🇵🇪", place: "Lima" },
  { flag: "🇵🇪" },
  { flag: "🇧🇷", place: "SP" },
  { flag: "🇧🇷", place: "Rio" },
  { flag: "🇧🇷" },
  { flag: "🇺🇾", place: "Montevideo" },
  { flag: "🇺🇾" },
  { flag: "🇪🇸", place: "Madrid" },
  { flag: "🇪🇸", place: "Barcelona" },
  { flag: "🇪🇸" },
  { flag: "🇪🇨", place: "Quito" },
  { flag: "🇻🇪", place: "Caracas" },
  { flag: "🇵🇦" },
  { flag: "🇨🇷" },
  { flag: "🇩🇴" },
  { flag: "🇬🇹" },
  { flag: "🇧🇴" },
  { flag: "🇵🇾" },
  { flag: "🇺🇸" },
  { flag: "🇬🇧" },
  { flag: "🇮🇹" },
  { flag: "🇵🇹" },
  { flag: "🇩🇪" },
  { flag: "🇫🇷" },
];

const GEN_TAGS = [
  "ok", "99", "24", "07", "88", "12", "45", "x", "zz", "pro", "fan", "play",
  "mx", "ar", "co", "cl", "pe", "br", "uy", "es", "vip", "real", "oficial",
  "trader", "gamer", "lucky", "spin", "jackpot", "galleta", "luna", "portal",
];

function pickGen<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateExtraPlayers(count: number): LivePlayer[] {
  const seen = new Set<string>(CORE_LIVE_PLAYERS.map((p) => p.handle));
  const out: LivePlayer[] = [];
  let guard = 0;

  while (out.length < count && guard < count * 40) {
    guard += 1;
    const first = pickGen(GEN_FIRST);
    const last = pickGen(GEN_LAST);
    const tag = pickGen(GEN_TAGS);
    const num = String(Math.floor(Math.random() * 9999)).padStart(
      Math.random() < 0.5 ? 3 : 4,
      "0",
    );
    const region = pickGen(GEN_FLAGS);

    const pattern = Math.floor(Math.random() * 10);
    let handle = "";
    switch (pattern) {
      case 0:
        handle = `@${first}.${last}`;
        break;
      case 1:
        handle = `@${first}_${last}`;
        break;
      case 2:
        handle = `@${first}${last}`;
        break;
      case 3:
        handle = `@${first}.${last}${num.slice(-2)}`;
        break;
      case 4:
        handle = `@${first}_${tag}`;
        break;
      case 5:
        handle = `@${first}${num}`;
        break;
      case 6:
        handle = `@user_${num}`;
        break;
      case 7:
        handle = `@player_${first}_${num}`;
        break;
      case 8:
        handle = `@${first}_${last}_${tag}`;
        break;
      default:
        handle = `@${last}_${first}${num.slice(-2)}`;
        break;
    }

    if (handle.length > 22) handle = handle.slice(0, 22);
    if (seen.has(handle)) continue;
    seen.add(handle);

    const player: LivePlayer = { handle, flag: region.flag };
    if (region.place && Math.random() < 0.35) player.place = region.place;
    out.push(player);
  }

  return out;
}

/** ~346 nombres curados + 700 generados = 1000+ jugadores únicos */
export const LIVE_PLAYERS_POOL: LivePlayer[] = [
  ...CORE_LIVE_PLAYERS,
  ...generateExtraPlayers(700),
];
